# Generated by Django 3.2.25 on 2024-09-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240923_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
