# Generated by Django 4.1 on 2024-09-19 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240918_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='semester',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.semester'),
        ),
        migrations.AddField(
            model_name='registration',
            name='session',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
