# Generated by Django 3.2.25 on 2024-10-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_level_student_currentlevel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='currentlevel',
            new_name='currentLevel',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='entrySessions',
            new_name='entrySession',
        ),
    ]
