# Generated by Django 3.2.25 on 2024-10-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
        migrations.AddField(
            model_name='programme',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
