# Generated by Django 3.2.25 on 2024-11-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmregister',
            name='totalUnits',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
