# Generated by Django 3.2.25 on 2024-11-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_confirmregister_totalunits'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='grade_type',
            field=models.CharField(choices=[('passed', 'passed'), ('failed', 'failed')], default=None, max_length=20, null=True),
        ),
    ]
